# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.event_listener.password:
        class: AppBundle\EventListener\PasswordListener
        arguments:
            - '@security.password_encoder'
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    menu_renderer.sidebar:
        class: AppBundle\Menu\Renderer\Sidebar
        arguments:
            - '@knp_menu.matcher'
            - '%knp_menu.renderer.list.options%'
            - '%kernel.charset%'
        tags:
            - { name: knp_menu.renderer, alias: sidebar }
