# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.event_listener.password:
        class: AppBundle\EventListener\PasswordListener
        arguments:
            - '@security.password_encoder'
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    menu_renderer.sidebar:
        class: AppBundle\Menu\Renderer\Sidebar
        arguments:
            - '@knp_menu.matcher'
            - '%knp_menu.renderer.list.options%'
            - '%kernel.charset%'
        tags:
            - { name: knp_menu.renderer, alias: sidebar }

    app.form.type.uploaded:
        class: AppBundle\Form\Type\UploadedFileType
        arguments:
            - '@stof_doctrine_extensions.uploadable.manager'
        tags:
            - { name: form.type }

    app.form.type.article:
        class: AppBundle\Form\Type\ArticleType
        arguments:
            - '@=service("doctrine").getRepository("AppBundle:Tag")'
            - '@=service("kernel").getRootDir()'
            - '@=service("request_stack").getCurrentRequest().attributes.get("article")'
        tags:
            - { name: form.type }
